# Generated by Django 2.2.9 on 2020-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='Новая услуга', max_length=500, verbose_name='Название'),
        ),
    ]
