# Generated by Django 2.2.9 on 2020-06-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelwork', '0003_auto_20200603_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'verbose_name': 'Изображение услуги', 'verbose_name_plural': 'Изображения услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_title',
            field=models.CharField(default='', max_length=100, verbose_name='Короткое название'),
            preserve_default=False,
        ),
    ]
